### PR TITLE
Faster generation of candidates

### PR DESCRIPTION
**Pull request by boidolr**
On my machine the test case with of 124 checks runs roughly a second faster with these changes.

### CODE REVIEW

**Comment by fsondej** [comment]
I did some benchmarks

before changes:
english words        3.397s
english sentences    0.452s
polish words         0.849s

after adding __slots__:
english words        3.458s
english sentences    0.445s
polish words         0.860s

after chain:
english words        3.040s
english sentences    0.386s
polish words         0.765s

after generator expressions:
english words        3.081s
english sentences    0.396s
polish words         0.769s

generator expressions don't give any speedup, but make the code less readable so I reverted them

slots and chains are nice, they speedup about 15%

[ins] In [20]: %timeit -n1 -r1 count_words('autocorrect/data/plwiki.xml', 'pl')
before Counter:
25min 28s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
after Counter:
21min 48s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
and the output is the same

good job :)

**Comment by boidolr** [comment]
Interesting - for me the generators did make a difference. Though it wasn't as big as the others.
As there was no benefit for you the readability argument certainly wins here :)

**Comment by fsondej** [comment]
I added some benchmarks to unit tests, you can run them and write how it went. Speed fluctuates randomly, so the benchmarks take only minimum time from many runs so it should be more robust.

**Comment by boidolr** [comment]
Most of the time is now spent in `str.join` and the [check for existing words](https://github.com/fsondej/autocorrect/blob/64256aaaa924c36bd85c4fe40eaebeeeb82ab8ba/autocorrect/__init__.py#L35) so I do not think there is anything left which is reasonable to change.

**Pull request merged**
